const p2 = [
  {
    id: 1,
    titulo: "Soy leyenda",
    director: "Francis Lawrence",
    genero: "Ciencia ficción",
    duracion: 101,
    actores: "Will Smith",
  },
  {
    id: 2,
    name: "El rey león",
    director: "Rob Minkoff, Roger Allers",
    genero: "Musical/Infanti",
    duracion: 89,
    actores: "Simba",
  },
  {
    id: 3,
    name: "La marca del demonio",
    director: "Diego Cohen",
    genero: "Terror",
    duracion: 82,
    actores: "Eduardo Noriega",
  },
  {
    id: 4,
    name: "A todo gas",
    director: "Rob Cohen",
    genero: "Aventura",
    duracion: 106,
    actores: "Vin Diesel, Paul Walker",
  },
  {
    id: 5,
    name: "The Joker",
    director: "Todd Phillips",
    genero: "Drama/Crimen",
    duracion: 122,
    actores: "Joaquin Phoenix",
  },
  {
    id: 6,
    name: "The Witcher: la pesadilla del lobo",
    director: "Kwang Il Han",
    genero: "Fantasía/Aventura",
    duracion: 83,
    actores: "Henry Cavill",
  },
  {
    id: 7,
    name: "El rey de la montaña",
    director: "Gonzalo López-Gallego",
    genero: "Suspense/Acción",
    duracion: 120,
    actores: "María Valverde",
  },
  {
    id: 8,
    name: "El rey de todo del mundo",
    director: "Carlos Saura",
    genero: "Musical",
    duracion: 95,
    actores: "Ana de la reguera",
  },
];

module.exports = p2;
